RHCLOUD-33802 Migrate clean job to a postgres container
RedHatInsights/payload-tracker-go pull request #200
Opened 2024-07-19 18:13 UTC by josejulio

## What?

RHCLOUD-33802 Start using a postgres image to run the clean jobs

## Why?
Latest base images prevent us from installing postgres12 and we had to find other way to do it.

## How?
Using volumes to mount our scripts in the postgresql image instead of building a dedicated image

## Testing
No

## Anything Else?
- Checking what else could be removed because of this change
- I'll add comments linking to names that were obtained from other repositories/sources.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-07-19 18:17 UTC, josejulio commented on deployments/clowdapp.yml
> +              name: playbook-tracker-go-db-cleaner-config
This `ConfigMap` is defined below

2024-07-19 18:18 UTC, josejulio commented on deployments/clowdapp.yml
> +                name: payload-tracker-db-creds
This secret is taken from [our config](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/payload-tracker/namespaces/payload-tracker-prod.yml#L72).

2024-07-19 18:18 UTC, josejulio commented on deployments/clowdapp.yml
> +  value: postgres
This one matches our database name in the [database definition](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/terraform/resources/insights/stage/rds/rds-payload-tracker-stage-12.yml#L3).

2024-07-19 20:53 UTC, tahmidefaz approved these changes
The changes looks good to me. If there are no issues, we can merge this in next week. Let it sit in stage for a few days, before promoting to prod. :smile:

2024-07-22 15:54 UTC, dehort requested changes
I like this approach.  I think this is a great idea!

I left a couple of comments.  

Thanks!!

2024-07-22 16:08 UTC, josejulio commented on deployments/clowdapp.yml
> +            value: ${DB_NAME}
I wasn't aware from that - is there any reference or doc about the database name?

2024-07-22 16:09 UTC, josejulio commented on deployments/clowdapp.yml
> +                name: virtual-assistant-db
yes, copy/pasta mistake, thanks!

2024-07-22 16:48 UTC, josejulio commented on deployments/clowdapp.yml
> +                name: virtual-assistant-db
Ref is here: https://gitlab.cee.redhat.com/service/app-interface#manage-rds-databases-via-app-interface-openshiftnamespace-1yml 
Thanks @dehort !

2024-07-22 16:50 UTC, josejulio commented
@dehort Just updated the code to address the review. 

Updated to use the `db.name` content from the secret and using `payload-tracker` instead of `playbook-tracker` :sweat_smile:

2024-07-22 18:35 UTC, dehort approved these changes
Looks good to me!

2024-07-22 18:38 UTC, dehort commented
Thank you @josejulio !!

2024-07-22 18:38 UTC, merged